# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Simon Iong
email: manin.iong@gmail.com
author: Simon Iong
description: > # this means to ignore newlines until "baseurl:"
  Simon Iong's personal thoughts on software development & life hacking
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://simoniong.info" # the base hostname & protocol for your site
twitter_username: simoniong
github_username: simoniong

# Build settings
markdown: kramdown
