# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Simon Iong
email: manin.iong@gmail.com
author: Simon Iong
description: > # this means to ignore newlines until "baseurl:"
  Simon Iong's personal thoughts on software development & life hacking
baseurl: ""
url: "http://simoniong.info"
twitter_username: simoniong
github_username: simoniong

# Build settings
markdown: kramdown
kramdown:
  input: GFM

excerpt_separator: "\n\n\n"
